version: 0
metadata:
  name: "taskcluster-docs"
  description: "Automation for taskcluster-docs"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
        - "auth:aws-s3:read-only:taskcluster-raw-docs/*"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
    payload:
      maxRunTime: 3600
      image: "node:9.4"
      features:
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "--login"
        - "-c"
        - >-
            git clone $GITHUB_BASE_REPO_URL &&
            cd taskcluster-docs &&
            git fetch origin pull/$GITHUB_PULL_REQUEST/head:pull-request &&
            git checkout pull-request &&
            bash util/taskcluster-build.sh pull-request
    metadata:
      name: "taskcluster-docs check"
      description: "Run `gulp check` to verify docs well-formedness`"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
        - "auth:aws-s3:read-only:taskcluster-raw-docs/*"
        - "auth:aws-s3:read-write:docs-taskcluster-net/"
        - "secrets:get:project/taskcluster/tc-docs/mozillians"
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
          - publish-test
    payload:
      maxRunTime: 3600
      image: "node:9.4"
      features:
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "--login"
        - "-c"
        - >-
            git clone $GITHUB_HEAD_REPO_URL &&
            cd taskcluster-docs &&
            git checkout $GITHUB_HEAD_BRANCH &&
            bash util/taskcluster-build.sh push
    metadata:
      name: "taskcluster-docs publish"
      description: "Run `gulp publish` to publish the docs to S3`"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
