$schema: http://json-schema.org/draft-04/schema#
id: https://docs.taskcluster.net/manual/tasks/actions/schema.yml
title: Schema for Exposing Actions
description: |
  This document specifies the schema for the `public/actions.json` used by
  _decision tasks_ to expose actions that can be triggered by end-users.

  For the purpose of this document the _consumer_ is the user-interface that
  displays task results to the end-user and allows end-users to trigger actions
  defined by `public/actions.json`. A _consumer_ might be Treeherder.
  The _end-user_ is a developer who is inspecting the results, and wishes to
  trigger actions.
type: object
properties:
  version:
    enum: [1]
    type: integer
  variables:
    type: object
    description: |
      Additional variables included in JSON-e context.
    additionalProperties: true
  actions:
    type: array
    description: |
      List of actions that can be triggered.
    items:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          description: |
            The name of this action.  This is used by user interfaces to
            identify the action. 
        title:
          type: string
          maxLength: 255
          description: |
            Title text to be displayed on the button or link triggering the action.
        description:
          type: string
          maxLength: 4096
          description: |
            Human readable description of the action in markdown. This
            can be displayed in a tooltip, popup and/or dialog when triggering
            the action.
        kind:
          enum:
            - task
          description: |
            Specifies the kind of action this is.
        context:
          type: array
          default: []
          items:
            type: object
            additionalProperties:
              type: string
              maxLength: 4096
            title: tag-set
            description: |
              A set of key-value pairs specifying a _tag-set_.
          description: |
            The `context` property determines in what context the action is
            relevant. Thus, what context the action should be presented to the
            end-user.
        schema:
          $ref: http://json-schema.org/schema
          description: |
            JSON schema for user input to the action.  If this property is omitted,
            then the input is `null`.
        task:
          type: object
          title: task template
          description: |
            Task template for triggering the action.

            When an action have been selected in the appropriate context and
            input satisfying the `schema` (if any) has been collected. The
            action is triggered by parameterizing the task template given in
            this property, and creating the resulting task.

            The template is an object that is parameterized using
            [JSON-e](https://github.com/taskcluster/json-e), with the context
            described in the documentation.
      additionalProperties: false
      required:
        - title
        - description
        - kind
        - task
additionalProperties: false
required:
  - version
  - actions
  - variables
